### ISSUE TITLE
Bad layout in file dialog

### ISSUE THREAD

**Issue by FreeSlave** [dayllenger/beamui#1]
![screenshot from 2018-10-25 22-21-11](https://user-images.githubusercontent.com/5596503/47524916-a76d6280-d8a4-11e8-9420-fdab8fe35962.png)
Happens when clicking on other item on the left panel or on some path part. SDL backend.
Also the list on the left becomes thinner on every redraw. Some issue with rounding?

**Comment by dayllenger** [comment]
This happens when grid [autofit is active](https://github.com/dayllenger/atoll/blob/d44e3e5abb2c0af03de66819091672f82822c68a/src/atoll/dialogs/filedlg.d#L519), may be related to horizontal scrollbar. Need to investigate this.

**Comment by dayllenger** [comment]
[Fixed](https://github.com/dayllenger/atoll/commit/e6a83171ab63294a884e3dc706b2493add7df3fc)
