### ISSUE TITLE
TableLayout: colspan / rowspan support?

### ISSUE THREAD

**Issue by saaadel** [dayllenger/beamui#11]
I could not figure out how to make the union of table cells for some components - colspan / rowspan
For example a two-column text field.
Could you provide an example (if it possible)?

**Comment by dayllenger** [comment]
It is not possible yet. Tables are a weak point currently, I'd like to not advance them, but to replace with a subset of CSS Grid in a near future.

If you really need spans, you may assemble layout with `row` and `column` only (they don't support percent sizes though).

**Comment by saaadel** [comment]
got it.
