### ISSUE TITLE
How can i use this ?

### ISSUE THREAD

**Issue by kcvinker** [dayllenger/beamui#12]
Hi,
I would like to run the examples and test this library. But i couldn't find any instructions. Please help.

**Comment by dayllenger** [comment]
1. clone this repository, or download zip and unpack it
2. do `dub run :canvas` or `dub run :css` command in the repository folder. On Windows, it should work fine out of the box.

`canvas` and `css` are the only runnable examples right now.

**Comment by kcvinker** [comment]
Hi,
Thanks for the reply. I just tried as you said and this is the result of canvas
![Captured_000033](https://user-images.githubusercontent.com/8840907/81934868-50a5b600-960d-11ea-8e22-6011c94073b7.jpg)

And running css also results in same error.

**Comment by dayllenger** [comment]
Update and try now.

**Comment by kcvinker** [comment]
Thanks a lot. It worked beautifully.
