### ISSUE TITLE
Linking error on Ubuntu

### ISSUE THREAD

**Issue by aberba** [dayllenger/beamui#18]
Playing with beamui. I'm able to modify and run the **examples** without any issue. However when I tried to add it as a local dependency using dub like:
```json
{
...
"dependencies":{
	"beamui":{
            "versions": "~master",
            "path": "./beamui"
    	}
}
```

I get this linking error:

```sh
beamui-demo ~master: building configuration "application"...
Linking...
.dub/build/application-debug-linux.posix-x86_64-dmd_2092-1496F27FB42CD3101C37430C37C4FFB9/beamui-demo.o: In function `initPlatformProxy':
/home/aberba/workspace/d/beamui-demo/beamui/src/beamui/platforms/common/platform.d:2625: undefined reference to `initPlatform'
collect2: error: ld returned 1 exit status
Error: linker exited with status 1
/usr/bin/dmd failed with exit code 1.
```

How do I resolve this issue?

**Comment by dayllenger** [comment]
There should be `beamui:platforms` dependency there and `mixin RegisterPlatforms;` in the code.

**Comment by aberba** [comment]
Awesome! Its works now. Really can't weight for a beta (or something) public release. As a react guy, beamui really feels natural. Good work.
