### ISSUE TITLE
Some differents to dlangui?

### ISSUE THREAD

**Issue by sr-tream** [dayllenger/beamui#2]
What is changed compared to dlangui? Are there any differences other than a cleaner repository and a modified light theme?

**Comment by dayllenger** [comment]
None of the features is stable, they're all experimental.

What is here today:
* CSS, which is great and already familiar to web, GTK+ or Qt developers
* actions now work entirely on delegates, not on id-switch-case stuff
* gettext localization - very simple and uses existing toolchain
* transitions and animations (very raw)
* refactored codebase, improved and simplified API (high code and API quality is essential)
* some specific changes like another measure-layout system
* bugfixes, optimizations, growing docs

What's new I want to implement:
* reactive (event stream) paradigm
* embedding into existing OpenGL (or not) renderer
* better layouts
* missing controls such as color/font pickers, spin boxes, etc.
* formatted text
* SVG and painting API
* ...

What was broken and will be revived:
* Android support
* console build - need to integrate it with CSS and make a theme
* HiDPI
* DML - may be made compile-time only/replaced/removed/...

What was removed:
* DOM - some dead code
* Scene3d - some irrelevant code
* SFML backend - not needed if we'll implement embedding

I will add all the differents to the readme some day.

**Comment by sr-tream** [comment]
Thx

**Comment by saaadel** [comment]
Please, place this in README.md

Edit: I am here for CSS support
