### ISSUE TITLE
Where should the beamui directory be located?

### ISSUE THREAD

**Issue by Keyn1** [dayllenger/beamui#22]
git clone https://github.com/dayllenger/beamui.git  -its OK
but beamui is downloaded to the current folder, for example c:\dlang

now I have
c:\Dlang\
   dmd2\
   beamui\

I do
c:\DlangPrg>dub init hello beamui
Couldn't find package: beamui

copy beamui -> C:\Dlang\dmd2\src\beamui
Couldn't find package: beamui

Нужен хоть какой-нибудь хелп как этим вообще пользоваться.

**Comment by dayllenger** [comment]
Ну просто нужно вручную добавить зависимость, как сделано в примерах. Пакета пока нет в dub registry.

dub.json:
```json
"dependencies": {
	"beamui": {"path": "../beamui"},
	"beamui:platforms": {"path": "../beamui"}
}
```

**Comment by Keyn1** [comment]
я добавил зависимости в файл dub.json
запускаю dub run

C:\DlangPrg\hellogui>dub run
Performing "debug" build using C:\Dlang\dmd2\windows\bin\dmd.exe for x86_64.
bindbc-loader 0.2.1: target for configuration "noBC" is up to date.
bindbc-freetype 0.8.0: target for configuration "dynamic" is up to date.
bindbc-opengl 0.12.0: target for configuration "dynamic" is up to date.
inilike 1.1.0: target for configuration "library" is up to date.
isfreedesktop 0.1.1: target for configuration "library" is up to date.
xdgpaths 0.2.5: target for configuration "library" is up to date.
icontheme 1.2.2: target for configuration "library" is up to date.
mofile 0.2.1: target for configuration "library" is up to date.
beamui 0.8.0+commit.359.gb86f674: target for configuration "library" is up to date.
beamui:platforms 0.8.0+commit.359.gb86f674: target for configuration "library-windows" is up to date.
hellogui ~master: building configuration "application"...
Linking...
beamui.lib(platform_289c_246.obj) : error LNK2019: ссылка на неразрешенный внешний символ initPlatformProxy в функции _D6beamui9platforms6common8platform6GuiApp10initializeMFZb.
.dub\build\application-debug-windows-x86_64-dmd_2094-995BBAFD3D3726B225F1C6E5ECBB3AC5\hellogui.exe : fatal error LNK1120: неразрешенных внешних элементов: 1
Error: linker exited with status 1120
C:\Dlang\dmd2\windows\bin\dmd.exe failed with exit code 1.

В чем может быть проблема?

а пример с сайта взял
// helloworld
import beamui;

int main()
{
    GuiApp app;
    if (!app.initialize())
        return -1;

    Window window = platform.createWindow("My Window");
    window.show();
    // run event loop
    return platform.runEventLoop();
}



Саму библиотеку куда по правилам ложить, в каталог C:\Dlang или C:\Dlang\dmd2?

**Comment by Keyn1** [comment]
И еще если качаю с сайта библиотеку, то качается beamui-master, а если командой в консоле beamui, а мне какая нужна?

**Comment by Keyn1** [comment]
put "beamui" in C:\Dlang\beamui
fix the file: dub.json

{
	"authors": [
		"Keyn"
	],
	"copyright": "2020",
	"description": "a",
	"license": "proprietary",
	"name": "hellogui",
	"dependencies": {
		"beamui": {"path": "C:\\Dlang\\beamui"},
		"beamui:platforms": {"path": "C:\\Dlang\\beamui"}
	}
}

compilation is successful
