### ISSUE TITLE
No libs

### ISSUE THREAD

**Issue by DarkHole1** [dayllenger/beamui#3]
I tried to compile test projects and got an error.
`E:\Projects\atoll\libs\windows-x86\libfreetype-6.dll: The system cannot find the path specified.`
Looking at the original dlangui, I realized that this folder contains the necessary libraries and deleted in the fork.
Why is it removed? Why is this not written anywhere? Where to get its contents?

**Comment by dayllenger** [comment]
Sorry, working on linux I didn't notice that they are gitignored, stupid mistake. Fixed now.
BTW, I don't recommend to write some projects based on this library today, because various breaking changes come often and without changelog.

**Comment by DarkHole1** [comment]
I think it is obvious that you should not write something serious on libraries with version <1.0.0. But, unfortunately, D doesn't have too many libraries for UI.
