### ISSUE TITLE
Создание подсказки вне области слоя для которого данная подсказка создаётся.

### ISSUE THREAD

**Issue by White-116** [dayllenger/beamui#8]
![bugs](https://user-images.githubusercontent.com/7798768/71644564-7fb13000-2cdb-11ea-91d0-bd50bcb7fb9b.png)
См. выделенную овальную область.
Подсказка обновляется у мыши если даже она ушла из области слоя для которого данная подсказка создаётся.
Вероятно требуется проверка на фокус мыши при показе подсказки.

**Comment by dayllenger** [comment]
Пофиксил эту и предыдущую, тестируйте.
